### ISSUE TITLE
a bug on a Genus call in magma

### ISSUE THREAD

**Issue by edgarcosta** [JRSijsling/heuristic_endomorphisms#6]
Input:
```
from sage.all import *
import heuristic_endomorphisms

digits= 600
QQx = PolynomialRing(QQ, 'x');
g = QQx([-1, 5, -8, 4, -1, 1])
print "y^2 = %s" % latex(g)
End = heuristic_endomorphisms.EndomorphismData(g, prec = digits)

```

Output:
```
y^2 = x^{5} - x^{4} + 4 x^{3} - 8 x^{2} + 5 x - 1
Traceback (most recent call last):
  File "bug.py", line 8, in <module>
    End = heuristic_endomorphisms.EndomorphismData(g, prec = digits)
  File "<string>", line 16, in __init__
  File "/Applications/sage-dev/local/lib/python2.7/site-packages/sage/interfaces/magma.py", line 1803, in __call__
    nvals=nvals)
  File "/Applications/sage-dev/local/lib/python2.7/site-packages/sage/interfaces/magma.py", line 1161, in function_call
    return self._do_call(fun, nvals)
  File "/Applications/sage-dev/local/lib/python2.7/site-packages/sage/interfaces/magma.py", line 1211, in _do_call
    return self(code)
  File "/Applications/sage-dev/local/lib/python2.7/site-packages/sage/interfaces/magma.py", line 791, in __call__
    A = Expect.__call__(self, x)
  File "/Applications/sage-dev/local/lib/python2.7/site-packages/sage/interfaces/interface.py", line 245, in __call__
    return cls(self, x, name=name)
  File "/Applications/sage-dev/local/lib/python2.7/site-packages/sage/interfaces/expect.py", line 1388, in __init__
    raise_(TypeError, x, sys.exc_info()[2])
  File "/Applications/sage-dev/local/lib/python2.7/site-packages/sage/interfaces/expect.py", line 1383, in __init__
    self._name = parent._create(value, name=name)
  File "/Applications/sage-dev/local/lib/python2.7/site-packages/sage/interfaces/interface.py", line 435, in _create
    self.set(name, value)
  File "/Applications/sage-dev/local/lib/python2.7/site-packages/sage/interfaces/magma.py", line 626, in set
    out = self.eval("%s:=%s" % (var, value))
  File "/Applications/sage-dev/local/lib/python2.7/site-packages/sage/interfaces/magma.py", line 560, in eval
    raise RuntimeError("Error evaluating Magma code.\nIN:%s\nOUT:%s" % (x, ans))
TypeError: Error evaluating Magma code.
IN:_sage_[4]:=Genus(_sage_[3]);
OUT:
>> _sage_[4]:=Genus(_sage_[3]);
                   ^
Runtime error in 'Genus': Bad argument types
Argument types given: RngUPolElt[FldRat]

```

**Comment by edgarcosta** [comment]
Ignore, now your X is a magma object, and not one equation.
